# Generated by Django 4.1.2 on 2023-09-21 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='depot',
            fields=[
                ('depot_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('depot_txt', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('deport_tel', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('deport_image', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('priority', models.BooleanField(default=True)),
                ('sortid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('internal_doc_no', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('storage_location', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('document_date', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('case_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('court', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('var_text1', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('var_text2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('var_text3', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('var_text4', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('var_text5', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('var_text6', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('var_text7', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('var_text8', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('operation', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('loadingCost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('packingCost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('landing_charge', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('other_fines', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('totsale', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('time', models.TimeField(blank=True, default=None, null=True)),
                ('user', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('trasferPostDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('trasferSavedDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('printed', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='master_data',
            fields=[
                ('material_no', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('girth', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('reduced_volume', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('time', models.TimeField(blank=True, default=None, null=True)),
                ('user', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('visible_material_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('qr_id', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('category', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('timber_class', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('specis', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('active', models.IntegerField(blank=True, default=None, null=True)),
                ('lot_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('value_grade', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('value_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('transCost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('depot', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('doc_date', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('gradeInCoupe', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('soldGrade', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('workingSheetNo', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('auctionLotSheetNo', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, max_length=10, null=True)),
                ('yiel_d', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, max_length=10, null=True)),
                ('logType', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='movement',
            fields=[
                ('material_no', models.IntegerField(primary_key=True, serialize=False)),
                ('movement', models.IntegerField(blank=True, default=None, null=True)),
                ('old_ref_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('new_ref_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('bin', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('time', models.TimeField(blank=True, default=None, null=True)),
                ('user', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('document_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('valueGrade', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_txt', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('region_code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('priority', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_level',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_time', models.TimeField(blank=True, default=None, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('tel_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('users_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='region_auth',
            fields=[
                ('region_auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('deport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depot_id_set', to='stc.depot')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_id_set', to='stc.region')),
                ('user_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_id_set', to='stc.user_level')),
            ],
        ),
        migrations.AddField(
            model_name='depot',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_region_set', to='stc.region'),
        ),
    ]
